### ISSUE TITLE
Select a framework

### ISSUE THREAD

**Issue by shibanovp** [experienced-dev/java-starter-template#8]
We need:
* Auto-generated OpenAPI spec
* [OIDC](https://en.wikipedia.org/wiki/OpenID#OpenID_Connect_(OIDC))

**Comment by shibanovp** [comment]
I am leaning toward [Quarkus](https://quarkus.io/)

**Comment by VishovVladimir** [comment]
Why? For java more popular is Spring. It has many sub frameworks for cloud, k8s, and microservice architecture. And I have 4 yerars experience with it.

**Comment by shibanovp** [comment]
We are using Spring.
Fell free to reopen if needed.
